apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
spec:
  selector:
    matchLabels:
      app: etcd
  replicas: 2
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: nginx
          image: bitnami/etcd
          ports:
            - containerPort: